insert into students(Students_id, Roll, Students_Name, Gender, Institute, City, Scholarship_TK)
values (1, 101, 'Alice', 'Male', 'Tamirul Millat Kamil Madrasah', 'Khulna', 600),
(2, 102, 'Nowshin', 'Female', 'Darunnazat Siddikia Dakhil Madrasah', 'Khulna', 300),
(3, 103, 'Rupa', 'Male', 'Mohammadia Adarsha Alim Madrasah', 'Dhaka', 600),
(4, 104, 'Bob', 'Male', 'Darunnazat Siddikia Dakhil Madrasah', 'Comilla', 600),
(5, 105, 'Himal', 'Male', 'Tamirul Millat Kamil Madrasah', 'Savar', 300),
(6, 106, 'Alice', 'Male', 'Mohammadia Adarsha Alim Madrasah', 'Khulna', 300),
(7, 107, 'Shanto', 'Male', 'Darunnazat Siddikia Dakhil Madrasah', 'Gazipur', 300),
(8, 108, 'Topu', 'Male', 'Tamirul Millat Kamil Madrasah', 'Savar', 300),
(9, 109, 'Minar', 'Male', 'Mohammadia Adarsha Alim Madrasah', 'Dhaka', 300),
(10, 110, 'Afraim', 'Male', 'Darunnazat Siddikia Dakhil Madrasah', 'Dhaka', 600),
(11, 111, 'Ripon', 'Male', 'Tamirul Millat Kamil Madrasah', 'Sylhet', 600),
(12, 112, 'Bijoy', 'Male', 'Mohammadia Adarsha Alim Madrasah', 'Gazipur', 300),
(13, 113, 'Shagor', 'Male', 'Darunnazat Siddikia Dakhil Madrasah', 'Comilla', 300),
(14, 114, 'Mehzabin', 'Female', 'Tamirul Millat Kamil Madrasah', 'Gazipur', 600),
(15, 115, 'Nila', 'Female', 'Mohammadia Adarsha Alim Madrasah', 'Savar', 300),
(16, 116, 'Jerin', 'Female', 'Tamirul Millat Kamil Madrasah', null, 600),
(17, 117, 'Anika', 'Female', 'Darunnazat Siddikia Dakhil Madrasah', default, 300),
(18, 118, 'Nova', 'Female', 'Mohammadia Adarsha Alim Madrasah', '', 600);
